export const DEMO1 = 'DEMO1';
export const DEMO_TYPE = 'DEMO_TYPE';

//Login
export const REQUESET_IS_LOGIN = 'REQUESET_IS_LOGIN';
export const REQUESET_CREATE_TRIAL = 'REQUESET_CREATE_TRIAL';

//splash
export const REQUESET_GET_COUNT_IMAGE = 'REQUESET_GET_COUNT_IMAGE';

//requestIsCreateFolderImage
export const REQUESET_IS_CREATE_FOLDER_IMAGE =
  'REQUESET_IS_CREATE_FOLDER_IMAGE';

//requestIsCreateFolderImage
export const REQUESET_DATA_HISTORY_NGAY_CONG =
  'REQUESET_DATA_HISTORY_NGAY_CONG';

// Update location every 15 minutes
export const UPDATE_LOCATION = 'UPDATE_LOCATION';

export const REQUESET_DATA_HISTORY_NGAY_CONG_BAO_CAO =
  'REQUESET_DATA_HISTORY_NGAY_CONG_BAO_CAO';
export const REQUESET_DATA_HISTORY_NGAY_CONG_LOC_BAO_CAO =
  'REQUESET_DATA_HISTORY_NGAY_CONG_LOC_BAO_CAO';

//cham cong
export const REQUESET_DATA_CHAM_CONG = 'REQUESET_DATA_CHAM_CONG';
export const REQUESET_DATA_CHAM_CONG_FACE_ID =
  'REQUESET_DATA_CHAM_CONG_FACE_ID';

//Change password
export const REQUESET_CHANGE_PASSWORD = 'REQUESET_CHANGE_PASSWORD';
//Change thong tin ng dung
export const CHANGE_THONG_TIN_NGUOI_DUNG = 'CHANGE_THONG_TIN_NGUOI_DUNG';

export const REQUESET_LATE_SOON_ADMIN = 'REQUESET_LATE_SOON_ADMIN';
export const REQUESET_CHANGE_PASSWORD1 = 'REQUESET_CHANGE_PASSWORD1';

export const REQUESET_DETAIL_TIME_SHEET = 'REQUESET_DETAIL_TIME_SHEET';
export const REQUESET_DETAIL_TIME_SHEET_ALL = 'REQUESET_DETAIL_TIME_SHEET_ALL';

export const REQUESET_DATA_ADMIN_SHIFT = 'REQUESET_DATA_ADMIN_SHIFT';
export const REQUESET_DATA_IMAGE_CAMERA = 'REQUESET_DATA_IMAGE_CAMERA';
export const REQUESET_DATA_TIMEKEEPING_DAY = 'REQUESET_DATA_TIMEKEEPING_DAY';
export const REQUESET_DATA_LIST_MAP = 'REQUESET_DATA_LIST_MAP';

export const REQUESET_IS_CREATE_FACEID = 'REQUESET_IS_CREATE_FACEID';
export const REQUESET_IS_UPDATE_STATUS = 'REQUESET_IS_UPDATE_STATUS';

//lich su don xin phep
export const REQUESET_DATA_LIST_ACTIONS = 'REQUESET_DATA_LIST_ACTIONS';
export const REQUESET_DATA_LIST_CHUA_DUYET = 'REQUESET_DATA_LIST_CHUA_DUYET';
export const REQUESET_DATA_LIST_DA_DUYET = 'REQUESET_DATA_LIST_DA_DUYET';
export const REQUESET_DATA_LIST_TU_CHOI = 'REQUESET_DATA_LIST_TU_CHOI';
export const REQUESET_DELETE_ITEM_ORDER = 'REQUESET_DELETE_ITEM_ORDER';

export const REQUESET_DATA_GET_NUMBER_ORDER = 'REQUESET_DATA_GET_NUMBER_ORDER';
export const REQUESET_DATA_GET_REASON = 'REQUESET_DATA_GET_REASON';

// Get list block
export const GET_BAO_CAO_TONG_QUAN = 'GET_BAO_CAO_TONG_QUAN';
export const GET_DETAIL_TIME_SHEET = 'GET_DETAIL_TIME_SHEET';
export const GET_LIST_BLOCK_CA = 'GET_LIST_BLOCK_CA';
export const GET_LIST_BLOCK = 'GET_LIST_BLOCK';
export const GET_LIST_BLOCK_WITH_USER = 'GET_LIST_BLOCK_WITH_USER';

// User actions with application for change shift
export const CREATE_APPLICATION_FOR_CHANGE_SHIFT =
  'CREATE_APPLICATION_FOR_CHANGE_SHIFT';
export const UPDATE_APLLICATION_CHANGE_SHIFT_BY_USER =
  'UPDATE_APLLICATION_CHANGE_SHIFT_BY_USER';

// Admin actions with application for change shift
export const GET_LIST_APPLICATION_FOR_CHANGE_SHIFT =
  'GET_LIST_APPLICATION_FOR_CHANGE_SHIFT';
export const UPDATE_APLLICATION_CHANGE_SHIFT_BY_AMIN =
  'UPDATE_APLLICATION_CHANGE_SHIFT_BY_ADMIN';
export const DELETE_APPLICATION_CHANGE_SHIFT_BY_ADMIN =
  'DELETE_APPLICATION_CHANGE_SHIFT_BY_ADMIN';

//duyet nghi phep
export const REQUESET_MESSAGE_DUYET_NGHI_PHEP =
  'REQUESET_MESSAGE_DUYET_NGHI_PHEP';
export const REQUESET_DATA_DUYET_NGHI_PHEP = 'REQUESET_DATA_DUYET_NGHI_PHEP';
export const REQUESET_DATA_DUYET_NGHI_PHEP_DA_DUYET =
  'REQUESET_DATA_DUYET_NGHI_PHEP_DA_DUYET';
export const REQUESET_DATA_DUYET_NGHI_PHEP_TU_CHOI =
  'REQUESET_DATA_DUYET_NGHI_PHEP_TU_CHOI';

export const REQUESET_DELETE_DUYET_NGHI_PHEP_CHUA_DUYET =
  'REQUESET_DELETE_DUYET_NGHI_PHEP_CHUA_DUYET';
export const REQUESET_DELETE_DUYET_NGHI_PHEP =
  'REQUESET_DELETE_DUYET_NGHI_PHEP';

//duyet di muon ve som
export const REPON_DUYET_DI_MUON_VE_SOM = 'REPON_DUYET_DI_MUON_VE_SOM';
export const REQUESET_DATA_DUYET_DI_MUON_VE_SOM =
  'REQUESET_DATA_DUYET_DI_MUON_VE_SOM';
export const REQUESET_DATA_DUYET_DI_MUON_VE_SOM_DA_DUYET =
  'REQUESET_DATA_DUYET_DI_MUON_VE_SOM_DA_DUYET';
export const REQUESET_DATA_DUYET_DI_MUON_VE_SOM_TU_CHOI =
  'REQUESET_DATA_DUYET_DI_MUON_VE_SOM_TU_CHOI';

export const REQUESET_DELETE_DUYET_DI_MUON_VE_SOM_CHUA_DUYET =
  'REQUESET_DELETE_DUYET_DI_MUON_VE_SOM_CHUA_DUYET';
export const REQUESET_DELETE_DUYET_DI_MUON_VE_SOM =
  'REQUESET_DELETE_DUYET_DI_MUON_VE_SOM';

// Duyet change shift
export const RESPONSE_DUYET_CHANGE_SHIFT = 'RESPONSE_DUYET_CHANGE_SHIFT';
export const REQUESET_DATA_DUYET_CHANGE_SHIFT =
  'REQUESET_DATA_DUYET_CHANGE_SHIFT';
export const REQUESET_DATA_DUYET_CHANGE_SHIFT_DA_DUYET =
  'REQUESET_DATA_DUYET_CHANGE_SHIFT_DA_DUYET';
export const REQUESET_DATA_DUYET_CHANGE_SHIFT_TU_CHOI =
  'REQUESET_DATA_DUYET_CHANGE_SHIFT_TU_CHOI';
export const REQUESET_DELETE_DUYET_CHANGE_SHIFT =
  'REQUESET_DELETE_DUYET_CHANGE_SHIFT';
export const REQUESET_DELETE_DUYET_CHANGE_SHIFT_CHUA_DUYET =
  'REQUESET_DELETE_DUYET_CHANGE_SHIFT_CHUA_DUYET';

//duyet Quen cham cong
export const REPON_DUYET_QUEN_CHAM_CONG = 'REPON_DUYET_QUEN_CHAM_CONG';
export const REQUESET_DATA_DUYET_QUEN_CHAM_CONG =
  'REQUESET_DATA_DUYET_QUEN_CHAM_CONG';
export const REQUESET_DATA_DUYET_QUEN_CHAM_CONG_DA_DUYET =
  'REQUESET_DATA_DUYET_QUEN_CHAM_CONG_DA_DUYET';
export const REQUESET_DATA_DUYET_QUEN_CHAM_CONG_TU_CHOI =
  'REQUESET_DATA_DUYET_QUEN_CHAM_CONG_TU_CHOI';

export const REQUESET_DELETE_DUYET_QUEN_CHAM_CONG_CHUA_DUYET =
  'REQUESET_DELETE_DUYET_QUEN_CHAM_CONG_CHUA_DUYET';
export const REQUESET_DELETE_DUYET_QUEN_CHAM_CONG =
  'REQUESET_DELETE_DUYET_QUEN_CHAM_CONG';

//duyet di cong tac
export const REPON_DUYET_DI_CONG_TAC = 'REPON_DUYET_DI_CONG_TAC';
export const REQUESET_DATA_DUYET_DI_CONG_TAC =
  'REQUESET_DATA_DUYET_DI_CONG_TAC';
export const REQUESET_DATA_DUYET_DI_CONG_TAC_DA_DUYET =
  'REQUESET_DATA_DUYET_DI_CONG_TAC_DA_DUYET';
export const REQUESET_DATA_DUYET_DI_CONG_TAC_TU_CHOI =
  'REQUESET_DATA_DUYET_DI_CONG_TAC_TU_CHOI';

export const REQUESET_DELETE_DUYET_DI_CONG_TAC_CHUA_DUYET =
  'REQUESET_DELETE_DUYET_DI_CONG_TAC_CHUA_DUYET';
export const REQUESET_DELETE_DUYET_DI_CONG_TAC =
  'REQUESET_DELETE_DUYET_DI_CONG_TAC';

//nhiem vu check vi tri
export const REQUESET_DATA_CHECK_BUSINESS = 'REQUESET_DATA_CHECK_BUSINESS';
